### ISSUE TITLE
Search for files 

### ISSUE THREAD

**Issue by AdAvAn** [RanyAlbegWein/Tinypng#3]
### Thanks for your code.
A very cool script that just works and does its job.

I would suggest adding some functions for finding files.

In the current version, it is necessary to specify the file names and paths for loading. This is cool, but in my example there are 3,500 files and they are all in different folders.

An additional solution for me was the use of the "find" command, which searches for files by extension along a given path. In the event that the file was found it is sent to "tinypng", with information about the name and path of the location.

`find /path -type f \( -name "*.png" -or -name "*.jpg" -or -name "*.jpeg" \) -print -exec bash -c '/path/tinypng --file {} --download $(dirname {}) --overwrite --print --key "00000000000000000"' \;`

It is very simple, it allowed me to convert my 3,500 without having to do the "tinypng" configuration for each directory.

Perhaps this example can be useful to someone else, if possible, add it to README.md

**Comment by RanyAlbegWein** [comment]
You're welcome!
I'll add an example to README.md

Thank you very much for the idea!
